// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js charge .env + .env.development/.env.production selon la commande, mais la
// CLI Prisma (migrate, studio, seed...) ne connaît que .env par défaut — on charge donc
// explicitement .env.development ici pour couvrir l'usage local le plus courant.
// Pour une migration en prod, exporte les variables de .env.production dans le shell avant
// d'appeler `prisma migrate deploy` (voir la section Déploiement du README).
config();
config({ path: ".env.development", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
